-- Run once in Snowsight as ACCOUNTADMIN if the Cortex REST call returns 403.
-- Replace SUNA if the PAT belongs to a different Snowflake user.
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_REST_API_USER TO ROLE ACCOUNTADMIN;
ALTER USER SUNA SET DEFAULT_ROLE = ACCOUNTADMIN;

-- If your account uses a dedicated application role instead, use this pattern:
-- CREATE ROLE IF NOT EXISTS SNOWVOCA_CORTEX_ROLE;
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_REST_API_USER TO ROLE SNOWVOCA_CORTEX_ROLE;
-- GRANT ROLE SNOWVOCA_CORTEX_ROLE TO USER SUNA;
-- ALTER USER SUNA SET DEFAULT_ROLE = SNOWVOCA_CORTEX_ROLE;
